// ==UserScript==
// @name         claude2cn-design
// @namespace    https://github.com/jyking/claude2cn/
// @homepageURL  https://github.com/jyking/claude2cn/
// @author       jyking
// @version      1.7.4
// @description  Claude 中文汉化 Design 页面词库规则，配合主插件使用
// @license      MIT
// ==/UserScript==
var DESIGN_TRANSLATIONS = {
  "(all optional)": "（均可选）",
  "(or name of design system)": "（或设计系统名称）",
  "Add": "添加",
  "Add fonts, logos and assets": "添加字体、Logo 和资源",
  "Add screenshot": "添加截图",
  "Add to favorites": "收藏",
  "Allow pop-ups for this site, then try again": "请允许此网站的弹出窗口，然后重试",
  "Any other notes?": "还有其他备注吗？",
  "Arrow (A)": "箭头 (A)",
  "Attach code": "附加代码",
  "Attach codebase": "附加代码库",
  "Attach designs": "附加设计",
  "Attach file": "附加文件",
  "Attach files": "附加文件",
  "Back": "返回",
  "Back to projects": "返回项目",
  "Bring your tools and data into Claude": "将你的工具和数据接入 Claude",
  "browse": "浏览",
  "Browse directory": "浏览目录",
  "Browse projects": "浏览项目",
  "by Anthropic Labs": "由 Anthropic Labs 出品",
  "Cancel": "取消",
  "Chat": "对话",
  "Chat history": "对话历史",
  "Check": "确认",
  "Claude Code browser sessions aren't available for your organization": "你的组织不支持 Claude Code 浏览器会话",
  "Clear all": "清除全部",
  "Close": "关闭",
  "Company name and blurb": "公司名称与简介",
  "Configure access": "配置访问权限",
  "Configured Claude.ai connectors will also be available here": "已配置的 Claude.ai 连接器也将在此显示",
  "Connect": "连接",
  "Connect Figma to continue": "连接 Figma 以继续",
  "Connect GitHub": "连接 GitHub",
  "Connect GitHub to continue": "连接 GitHub 以继续",
  "Connected": "已连接",
  "Connectors": "连接器",
  "Continue to generation": "继续生成",
  "Conversations": "会话",
  "Copied!": "已复制！",
  "Copy": "复制",
  "Copy command": "复制命令",
  "Copy link": "复制链接",
  "Create": "创建",
  "Create and update issues": "创建并更新 Issue",
  "d ago": "天前",
  "Describe what you want to create...": "描述你想要创建的内容…",
  "Design Files": "设计文件",
  "Design system": "设计系统",
  "Design System": "设计系统",
  "Design System appears in organization's design-system picker when published": "发布后将出现在组织的设计系统选择器中",
  "Design systems": "设计系统",
  "Designs grounded in real context turn out better.": "基于真实背景的设计效果更好。",
  "Disconnect": "断开连接",
  "Disconnecting…": "正在断开…",
  "Dismiss": "关闭",
  "Docs": "文档",
  "Don't invent colors, type, spacing, or components not grounded here.": "不得凭空创造颜色、字体、间距或组件。",
  "Download .zip": "下载 .zip",
  "Download zip instead": "改为下载 zip",
  "Drag a folder here or": "拖放文件夹到此处，或",
  "Drag files here or": "拖放文件到此处，或",
  "Drag in a Figma file": "拖入 Figma 文件",
  "Drop .fig here or": "拖放 .fig 到此处，或",
  "Drop files here": "拖放文件到此处",
  "Duplicate as template": "复制为模板",
  "Duplicate project": "复制项目",
  "Editable · custom fonts": "可编辑 · 自定义字体",
  "Editable · Google Slides fonts": "可编辑 · Google 幻灯片字体",
  "Editable · universal fonts": "可编辑 · 通用字体",
  "Enter key": "Enter 键",
  "Escape": "Esc",
  "Examples": "示例",
  "Export as PPTX": "导出为 PPTX",
  "Export each slide as a full-bleed PNG image. Text does not need to be editable.": "将每张幻灯片导出为全出血 PNG 图片，文字无需可编辑。",
  "Failed to create blob": "创建 blob 失败",
  "Failed to get canvas context": "获取画布上下文失败",
  "Failed to load napkin file": "加载 napkin 文件失败",
  "Fetch this design file, read its readme, and implement the relevant aspects of the design": "获取此设计文件，阅读其说明文档，并实现设计中的相关部分",
  "Figma downloads a .fig file. Drop it onto the chat input.": "Figma 会下载一个 .fig 文件，将其拖放到对话输入框中即可。",
  "File": "文件",
  "File type": "文件类型",
  "Files": "文件",
  "Folder": "文件夹",
  "Folders": "文件夹",
  "for a new line.": "换行。",
  "For computers with brand fonts installed. Best fidelity with full editability.": "适用于已安装品牌字体的电脑，保真度最高且完全可编辑。",
  "From the Figma web or desktop app:": "在 Figma 网页版或桌面应用中：",
  "Generate PPTX…": "正在生成 PPTX…",
  "Give the agent more detail on what to implement": "为智能体提供更多实现细节",
  "Go to **File → Save local copy...** (web: main menu → File).": "前往 **文件 → 保存本地副本...** （网页版：主菜单 → 文件）。",
  "Got it": "明白了",
  "Grab web element": "抓取网页元素",
  "h ago": "小时前",
  "Heading": "标题",
  "Hi-fi design": "高保真设计",
  "High fidelity": "高保真",
  "How to download": "如何下载",
  "How to download a .fig file": "如何下载 .fig 文件",
  "Image": "图片",
  "Images, docs, references, Figma links, or folders — Claude will use them as context.": "图片、文档、参考资料、Figma 链接或文件夹 — Claude 将以此为上下文。",
  "Import frames and design context": "导入画框与设计上下文",
  "Interactive prototype": "交互原型",
  "Investigate errors and traces": "排查错误与追踪信息",
  "Jot a thought…": "记录想法…",
  "just now": "刚刚",
  "Label": "标签",
  "Learn about Claude Design": "了解 Claude Design",
  "Learn how to get a .fig file": "了解如何获取 .fig 文件",
  "Link code from your computer": "链接本地代码",
  "Link code on GitHub": "链接 GitHub 上的代码",
  "Link local code...": "链接本地代码…",
  "Look up customers and charges": "查询客户与账单",
  "m ago": "分钟前",
  "Manage": "管理",
  "Manage connectors": "管理连接器",
  "New chat": "新建对话",
  "New prototype": "新建原型",
  "New sketch": "新建草图",
  "Only you can see your project by default.": "默认情况下，只有你能看到此项目。",
  "Open": "打开",
  "Open in Claude Code Web": "在 Claude Code Web 中打开",
  "Open the file in Figma.": "在 Figma 中打开文件。",
  "Options": "选项",
  "Org default · no assets yet": "组织默认 · 暂无资源",
  "Other": "其他",
  "over a week ago": "一周前",
  "Owner": "所有者",
  "Pan (H)": "平移 (H)",
  "Parsed locally in your browser — never uploaded.": "在本地浏览器中解析，不会上传到服务器。",
  "Paste": "粘贴",
  "Pen (P)": "钢笔 (P)",
  "Preview": "预览",
  "Private": "仅自己可见",
  "Project is too large to seed a Claude Code session": "项目过大，无法启动 Claude Code 会话",
  "Project menu": "项目菜单",
  "Project name": "项目名称",
  "Project title": "项目名称",
  "Prototype": "原型",
  "Provide examples of your design system and products": "提供设计系统和产品示例",
  "Query your database": "查询数据库",
  "Quick tutorial": "快速教程",
  "Read conversations and contacts": "读取会话与联系人",
  "Read repos, open pull requests": "读取仓库，发起拉取请求",
  "Read the attached README inside": "阅读其中附带的 README",
  "Recent": "最近",
  "Recommended": "推荐",
  "Reference another project": "引用其他项目",
  "Rename": "重命名",
  "Rename project": "重命名项目",
  "Research Preview": "研究预览",
  "Resume in Claude Code Web": "在 Claude Code Web 中继续",
  "Save": "保存",
  "Saved": "已保存",
  "Saving…": "保存中…",
  "Screenshot-based PPTX": "截图式 PPTX",
  "Search and read pages": "搜索并读取页面",
  "Search and read your Drive files": "搜索并读取你的云端硬盘文件",
  "Search channels and read threads": "搜索频道并读取消息串",
  "Search designs": "搜索设计",
  "Select (V)": "选择 (V)",
  "Select...": "选择…",
  "Send": "发送",
  "Send to Claude Code Web": "发送至 Claude Code Web",
  "Send to local coding agent": "发送至本地编码智能体",
  "Sends message": "发送消息",
  "Set up your design system": "设置你的设计系统",
  "Settings": "设置",
  "Shapes (R)": "形状 (R)",
  "Share": "分享",
  "Show chat": "显示对话",
  "Skills and design systems": "技能与设计系统",
  "Skip and continue": "跳过并继续",
  "Slide deck": "幻灯片",
  "Start with context": "从背景信息开始",
  "Starts a new line": "换行",
  "Sticky Note (S)": "便利贴 (S)",
  "Substitute all fonts with close matches from Google Fonts for Google Slides compatibility.": "将所有字体替换为 Google Fonts 中的近似字体，以兼容 Google 幻灯片。",
  "Substitute all fonts with web-safe equivalents (Arial, Georgia, Courier New).": "将所有字体替换为网络安全字体（Arial、Georgia、Courier New）。",
  "Subtitle": "副标题",
  "Teammates can comment": "团队成员可评论",
  "Teammates can edit": "团队成员可编辑",
  "Teammates can view": "团队成员可查看",
  "Tell us about your company and attach any design resources you have.": "介绍你的公司并附上现有的设计资源。",
  "Template": "模板",
  "Template appears in organization's template picker when published": "发布后将出现在组织的模板选择器中",
  "Text (T)": "文字 (T)",
  "The file is parsed locally in your browser and never uploaded.": "文件在本地浏览器中解析，不会上传到服务器。",
  "Thick brush": "粗画笔",
  "Thin brush": "细画笔",
  "This doesn't upload the whole codebase; Claude will copy selected files. For large codebases, we recommend attaching a frontend-focused subfolder.": "这不会上传整个代码库；Claude 将复制所选文件。对于大型代码库，建议附加前端相关的子文件夹。",
  "This is a binding choice for visual style — every visual must follow it.": "这是视觉风格的约束性选择，所有视觉内容均须遵循。",
  "To bring another project into this chat, paste its URL directly into the composer. Claude will pick it up and can read its files.": "将另一个项目的 URL 直接粘贴到输入框中，Claude 即可引用并读取该项目的文件。",
  "Trash": "删除",
  "Upload .fig file": "上传 .fig 文件",
  "Upload a .fig file": "上传 .fig 文件",
  "Uses Google Fonts for full compatibility when uploading to Google Slides.": "使用 Google Fonts 以确保上传至 Google 幻灯片时完全兼容。",
  "What works best: code and designs for your design system and your code products.": "最有效的方式：提供设计系统的代码与设计稿，以及你的代码产品。",
  "Where is this deck headed?": "这套幻灯片的用途是？",
  "Wireframe": "线框图",
  "You attached a Figma link, but Figma isn't connected yet. Connect now so we can read your design files during generation.": "你附加了 Figma 链接，但 Figma 尚未连接。立即连接，以便在生成过程中读取你的设计文件。",
  "You attached a GitHub repo, but GitHub isn't connected yet. Connect now so we can read private repos and fetch files on demand during generation.": "你附加了 GitHub 仓库，但 GitHub 尚未连接。立即连接，以便在生成过程中读取私有仓库并按需获取文件。",
  "Your browser blocked the new tab": "浏览器阻止了新标签页",
  "Your design": "你的设计",
  "Your designs": "你的设计",
  "Your designs and context are attached — please implement": "设计稿和上下文已附加，请开始实现"
};
